### ISSUE TITLE
AutoRoute Link broken

### ISSUE THREAD

**Issue by wlai2014** [erdc-cm/AutoRoutePy#3]
Hi Alan,

The link for AutoRoute is broken:
 https://github.com/erdc-cm/AutoRoute/tree/cgdal

Could you fix this? Thank you.

**Comment by snowman2** [comment]
It actually does work. But it is private.

**Comment by wlai2014** [comment]
Thank you, Alan.

Without installing AutoRoute, is the AutoRoutePy able to run AutoRoute?  The wiki example uses the auto_mng.run_autoroute() function. Are these AutoRoute executable inside AutoRoutePy?

**Comment by snowman2** [comment]
AutoRoute is required to run any simulations. If you need access to AutoRoute, @follumm is the person to talk to.
